# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experience.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='experience.proto',
  package='experience',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x65xperience.proto\x12\nexperience\"\xa4\x01\n\x05\x45xper\x12*\n\tnow_state\x18\x01 \x02(\x0b\x32\x17.experience.Exper.state\x12\x0e\n\x06\x61\x63tion\x18\x02 \x02(\x03\x12\x0e\n\x06reward\x18\x03 \x02(\x01\x12+\n\nnext_state\x18\x04 \x02(\x0b\x32\x17.experience.Exper.state\x12\x0c\n\x04\x64one\x18\x05 \x02(\x08\x1a\x14\n\x05state\x12\x0b\n\x03pos\x18\x01 \x03(\x01'
)




_EXPER_STATE = _descriptor.Descriptor(
  name='state',
  full_name='experience.Exper.state',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='experience.Exper.state.pos', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=197,
)

_EXPER = _descriptor.Descriptor(
  name='Exper',
  full_name='experience.Exper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='now_state', full_name='experience.Exper.now_state', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='experience.Exper.action', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reward', full_name='experience.Exper.reward', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_state', full_name='experience.Exper.next_state', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='done', full_name='experience.Exper.done', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EXPER_STATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=197,
)

_EXPER_STATE.containing_type = _EXPER
_EXPER.fields_by_name['now_state'].message_type = _EXPER_STATE
_EXPER.fields_by_name['next_state'].message_type = _EXPER_STATE
DESCRIPTOR.message_types_by_name['Exper'] = _EXPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Exper = _reflection.GeneratedProtocolMessageType('Exper', (_message.Message,), {

  'state' : _reflection.GeneratedProtocolMessageType('state', (_message.Message,), {
    'DESCRIPTOR' : _EXPER_STATE,
    '__module__' : 'experience_pb2'
    # @@protoc_insertion_point(class_scope:experience.Exper.state)
    })
  ,
  'DESCRIPTOR' : _EXPER,
  '__module__' : 'experience_pb2'
  # @@protoc_insertion_point(class_scope:experience.Exper)
  })
_sym_db.RegisterMessage(Exper)
_sym_db.RegisterMessage(Exper.state)


# @@protoc_insertion_point(module_scope)
